name: CI test run

on:
  push:
    branches: [ main develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:

  makefile-test-run:
    strategy:
      matrix:
        std: [ "c++11", "c++14", "c++17", "c++20" ]
        cxx: [ "g++", "clang++" ]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggered by \"${{ github.event_name }}\", runner OS \"${{ runner.os }}\"."
      - name: Check out \"${{ github.repository }}\", branch \"${{ github.ref }}\."
        uses: actions/checkout@v3
      - name: Compile and run tests
        run: make test CXX=${{ matrix.cxx }} CXX_STD=${{ matrix.std }} PRINT_RESULTS=1

  makefile-test-coverage-linux-gcc:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggered by \"${{ github.event_name }}\", runner OS \"${{ runner.os }}\"."
      - name: Install lcov
        run: sudo apt install -y lcov
      - name: Check out \"${{ github.repository }}\", branch \"${{ github.ref }}\."
        uses: actions/checkout@v3
      - name: Check test coverage
        run: make coverage
